"""
Output guardrail — validates the agent's response before sending to the user.

Flow:
  1. Agent generates a reply
  2. Guardrail evaluates the reply against the full conversation context
     and NOTHA's scope of operation
  3. If approved → sends normally
  4. If rejected → attempts one correction with a specific instruction
  5. If still rejected → returns a generic safe fallback

Criteria (in order of severity):
  - Incoherence with the full conversation thread (not just the last message)
  - Out of scope relative to NOTHA's purpose
  - Sensitive data leakage (seller's floor price, buyer's ceiling limit)
  - Forbidden terms that reveal the underlying AI technology
  - Nonsense / truncated / broken text
"""
import json
import logging

logger = logging.getLogger("notha.guardrail")

_SAFE_FALLBACK = (
    "I had a technical issue formulating my response. "
    "Could you repeat what you need?"
)

# ── NOTHA scope description (reused in both prompts) ─────────────────────────
_NOTHA_SCOPE = """
NOTHA is a WhatsApp agent that facilitates buying and selling physical products
(furniture, electronics, vehicles, appliances, real estate items, etc.).
Its full scope includes:
  • Searching for products available near the user
  • Listing products for sale (photos, description, pricing, condition)
  • Price negotiation between buyer and seller via proxy agents
  • Payment coordination (Pix via Asaas, held in escrow until delivery confirmed)
  • Delivery and pickup logistics
  • User identification and basic profile management

NOTHA does NOT engage with: politics, religion, medical advice, financial
speculation, entertainment content, or any topic unrelated to physical product
trading. Politely redirecting off-topic requests is correct behaviour.
"""

_GUARDRAIL_PROMPT = """You are a quality and security auditor for NOTHA.

━━━ NOTHA — WHAT IT IS AND WHAT IT DOES ━━━
{scope}

━━━ USER CONTEXT ━━━
{context}

━━━ FULL CONVERSATION SO FAR ━━━
{history}

━━━ OBJECTIVE THAT WAS ATTEMPTED ━━━
{objective}

━━━ REPLY GENERATED BY THE AGENT ━━━
{reply}

━━━ EVALUATION INSTRUCTIONS ━━━
Evaluate the REPLY against the FULL CONVERSATION above, not just the last
message in isolation. A user may send several short messages, each with a
single word, abbreviation, or fragment — these must be interpreted together
with everything that was discussed before.

When an OBJECTIVE is provided, also verify the reply is consistent with
that objective — not perfectly complete, just not contradictory.

Reject (approved: false) if ANY of these unambiguous violations apply:

0. LANGUAGE_MISMATCH
   The reply is in a different language from the user's messages in the conversation history.
   Detect the user's language from their messages in the conversation. If the reply is clearly
   in a different language, reject it.
   Exceptions: proper nouns, brand names, product names, and single-word technical terms
   may appear in any language. Reject only when the body of the reply is in the wrong language.

1. INCOHERENCE
   The reply makes no sense when read against the full conversation thread.
   • Abbreviations, slang, emojis, and single-word replies MUST be interpreted
     in the context of the whole conversation before judging coherence.
   • Only reject if the reply is CLEARLY unrelated to the entire thread —
     not because of imperfect phrasing, tone differences, or a short user message.
   • Example of a correct rejection: user is negotiating a sofa price and
     the agent suddenly responds about the weather with no transition.

2. OUT_OF_SCOPE
   The reply engages substantively with a topic entirely outside NOTHA's purpose
   (e.g. gives political opinions, medical diagnoses, stock tips, or detailed
   content unrelated to physical product trading).
   • Politely declining such requests is NOT a violation.
   • Brief small-talk while steering back to NOTHA's purpose is NOT a violation.

3. DATA_LEAK
   The reply explicitly reveals to one party a value that is confidential to
   the other:
   • Reveals the seller's private minimum/floor price to the buyer, OR
   • Reveals the buyer's private maximum/ceiling limit to the seller.
   Stating the listed/asking price is fine — only leaking the private limit
   is a violation.

4. FORBIDDEN_TERM
   The reply mentions "GPT", "OpenAI", "Anthropic", "Claude", "Gemini", "LLM",
   "large language model", "artificial intelligence", "machine learning", or
   "algorithm" in a way that reveals the underlying AI technology to the user.

5. NONSENSE
   The reply is severely truncated mid-sentence, consists of random characters,
   or is entirely unintelligible. Informal language, abbreviations, regional
   slang, and emojis are NOT nonsense.

━━━ WHEN IN DOUBT, APPROVE ━━━
Only reject on clear, unambiguous violations. A borderline reply should be
approved — the agent's main system prompt already enforces quality.

━━━ RETURN FORMAT ━━━
Return ONLY valid JSON, no extra text:

Approved:
{{"approved": true}}

Rejected:
{{"approved": false, "category": "language_mismatch|incoherence|out_of_scope|data_leak|forbidden_term|nonsense", "reason": "<one concise sentence explaining the violation>"}}
"""

_CORRECTION_PROMPT = """The response you generated was rejected by the quality system.

━━━ NOTHA — WHAT IT IS AND WHAT IT DOES ━━━
{scope}

━━━ USER CONTEXT ━━━
{context}

━━━ FULL CONVERSATION SO FAR ━━━
{history}

━━━ OBJECTIVE THAT WAS ATTEMPTED ━━━
{objective}

━━━ REJECTION ━━━
Category : {category}
Reason   : {reason}

━━━ REJECTED REPLY ━━━
{rejected_reply}

Generate a corrected reply that:
  • Resolves the specific violation described above
  • Remains coherent with the full conversation thread shown
  • Is consistent with the objective above (when provided)
  • Stays within NOTHA's scope of operation
  • Uses a natural WhatsApp tone — concise, friendly, no jargon
  • Does NOT mention that a rejection occurred

Return ONLY the corrected reply text, nothing else."""


async def _call_guardrail_llm(messages: list[dict]) -> dict:
    """Calls the LLM in JSON mode to evaluate the response."""
    from llm import get_provider
    try:
        resp = await get_provider().complete(
            messages=messages,
            temperature=0.0,
            max_tokens=200,
            json_mode=True,
        )
        return json.loads(resp.text or '{"approved": true}')
    except Exception as e:
        logger.error("Guardrail LLM error: %s", e)
        return {"approved": True}


async def _call_correction_llm(messages: list[dict]) -> str:
    """Asks the LLM to correct the rejected response."""
    from llm import get_provider
    try:
        resp = await get_provider().complete(
            messages=messages,
            temperature=0.4,
            max_tokens=500,
        )
        return resp.text or _SAFE_FALLBACK
    except Exception as e:
        logger.error("Guardrail correction LLM error: %s", e)
        return _SAFE_FALLBACK


def _format_history(history: list[dict], max_messages: int = 30) -> str:
    """Formats the last N user/assistant messages in a readable form.

    Uses 30 messages by default so the guardrail sees as much context as
    possible — the whole point is to evaluate coherence against the full
    thread, not just the tail end.
    """
    recent = [m for m in history if m.get("role") in ("user", "assistant")][-max_messages:]
    lines = []
    for m in recent:
        role = "User" if m["role"] == "user" else "NOTHA"
        content = m.get("content") or ""
        if content:
            lines.append(f"{role}: {content[:400]}")
    return "\n".join(lines) if lines else "(conversa ainda sem histórico)"


async def validate_reply(
    reply: str,
    history: list[dict],
    context: str,
    user_message: str = "",
    objective: str = "",
    analytics_repo=None,
    phone: str | None = None,
    user_id: int | None = None,
) -> str:
    """Validates the generated response before sending to the user.

    Parameters:
      reply        — text generated by the agent
      history      — full conversation history (roles: user/assistant)
      context      — user context string (name, role, product, negotiation)
      user_message — last user message; if provided, appended to history for
                     the guardrail so the full thread is always complete
      objective    — what the agent was trying to achieve (from understand());
                     improves coherence checking precision

    Returns the original reply if approved, a corrected version if the
    correction passes, or a safe fallback if both attempts fail.
    """
    if not reply or not reply.strip():
        logger.warning("Guardrail: empty reply received — using fallback.")
        return _SAFE_FALLBACK

    # Build a complete history for the guardrail that always ends with the
    # user's latest message, even if the caller already appended it.
    guardrail_history = [m for m in history if m.get("role") in ("user", "assistant")]
    if user_message:
        last_user = next(
            (m["content"] for m in reversed(guardrail_history) if m["role"] == "user"),
            None,
        )
        if last_user != user_message:
            guardrail_history = guardrail_history + [{"role": "user", "content": user_message}]

    history_fmt = _format_history(guardrail_history)
    objective_fmt = objective or "(not specified)"

    # ── Phase 1: Evaluation ──────────────────────────────────────────────────
    evaluation_prompt = _GUARDRAIL_PROMPT.format(
        scope=_NOTHA_SCOPE,
        context=context or "não disponível",
        history=history_fmt,
        objective=objective_fmt,
        reply=reply,
    )
    result = await _call_guardrail_llm([{"role": "user", "content": evaluation_prompt}])

    if result.get("approved", True):
        return reply

    category = result.get("category", "unknown")
    reason = result.get("reason", "sem motivo especificado")
    logger.warning("Guardrail REJEITOU — category=%s | reason=%s", category, reason)

    # ── Phase 2: Correction attempt ──────────────────────────────────────────
    correction_prompt = _CORRECTION_PROMPT.format(
        scope=_NOTHA_SCOPE,
        context=context or "não disponível",
        history=history_fmt,
        objective=objective_fmt,
        category=category,
        reason=reason,
        rejected_reply=reply,
    )
    corrected_reply = await _call_correction_llm([{"role": "user", "content": correction_prompt}])

    # ── Phase 3: Re-evaluate the corrected reply ─────────────────────────────
    re_evaluation_prompt = _GUARDRAIL_PROMPT.format(
        scope=_NOTHA_SCOPE,
        context=context or "não disponível",
        history=history_fmt,
        objective=objective_fmt,
        reply=corrected_reply,
    )
    final_result = await _call_guardrail_llm([{"role": "user", "content": re_evaluation_prompt}])

    if final_result.get("approved", True):
        logger.info("Guardrail: resposta corrigida aprovada na segunda tentativa.")
        if analytics_repo:
            try:
                await analytics_repo.log_guardrail_event(
                    category=category, reason=reason,
                    was_corrected=True, used_fallback=False,
                    objective=objective or None, phone=phone, user_id=user_id,
                )
            except Exception:
                pass
        return corrected_reply

    logger.error(
        "Guardrail: resposta corrigida também rejeitada — usando fallback seguro. "
        "category=%s | reason=%s",
        final_result.get("category"),
        final_result.get("reason"),
    )
    if analytics_repo:
        try:
            await analytics_repo.log_guardrail_event(
                category=category, reason=reason,
                was_corrected=False, used_fallback=True,
                objective=objective or None, phone=phone, user_id=user_id,
            )
        except Exception:
            pass
    return _SAFE_FALLBACK
