"""
Output guardrail — validates the agent's response before sending to the user.

Flow:
  1. Normal response generation by the agent
  2. Guardrail analyses the response with context + history
  3. If approved → sends normally
  4. If rejected → attempts correction once with a specific instruction
  5. If still rejected → returns a generic safe fallback

Checks:
  - Coherence with the user's message and recent history
  - Sensitive data leakage (seller's minimum price, buyer's maximum limit)
  - Forbidden terms (GPT, AI, algorithm, OpenAI, Anthropic, Claude, etc.)
  - Monetary values invented without a tool call
  - Other non-negotiable NOTHA rules
"""
import json
import logging

logger = logging.getLogger("notha.guardrail")

_SAFE_FALLBACK = (
    "Tive um problema ao formular minha resposta. "
    "Pode repetir o que precisa?"
)

_GUARDRAIL_PROMPT = """You are a security auditor for NOTHA, a WhatsApp buy-and-sell system.

Check the GENERATED REPLY for hard violations only.

━━━ REPLY TO CHECK ━━━
{reply}

━━━ HARD VIOLATION CRITERIA ━━━
Reject (approved: false) ONLY if one of these clear violations is present:

1. DATA_LEAK: The reply explicitly states the seller's minimum/floor price to the buyer,
   or explicitly states the buyer's maximum/ceiling limit to the seller.
   (Normal price mentions like "the listed price is R$ 350" are NOT a violation.)

2. FORBIDDEN_TERM: The reply mentions "GPT", "OpenAI", "Anthropic", "Claude", "LLM",
   "artificial intelligence", "machine learning", or "algorithm" in a way that reveals
   the underlying AI technology.

3. NONSENSE: The reply consists of random characters, is severely truncated mid-sentence,
   or is entirely unintelligible (not just informal/slang — must be truly broken text).

━━━ IMPORTANT — DO NOT REJECT FOR ━━━
- Conversational flow choices (asking for confirmation, offering options)
- Abbreviations or informal language (e.g. "SP" = São Paulo, "BH" = Belo Horizonte)
- Reasonable replies to short/ambiguous messages
- Tone or style differences
- Minor incoherence or imperfect wording
- Repeating information from earlier in the conversation

When in doubt, APPROVE. Only reject on unambiguous hard violations.

━━━ RETURN FORMAT ━━━
Return ONLY valid JSON, no explanation:

If approved: {{"approved": true}}
If rejected: {{"approved": false, "category": "data_leak|forbidden_term|nonsense", "reason": "brief reason"}}
"""

_CORRECTION_PROMPT = """The response you generated was rejected by the quality system.

Rejection reason: {reason} (category: {category})

━━━ USER CONTEXT ━━━
{context}

━━━ LAST USER MESSAGE ━━━
{last_message}

━━━ REJECTED REPLY ━━━
{rejected_reply}

Generate a new response that specifically corrects the identified problem.
Keep the tone appropriate for WhatsApp. Be concise. Do not mention that a rejection occurred.
Return ONLY the new response, without any explanation."""


async def _call_guardrail_llm(messages: list[dict]) -> dict:
    """Calls the LLM in JSON mode to evaluate the response."""
    from llm import get_provider
    try:
        resp = await get_provider().complete(
            messages=messages,
            temperature=0.0,
            max_tokens=200,
            json_mode=True,
        )
        return json.loads(resp.text or '{"approved": true}')
    except Exception as e:
        logger.error("Guardrail LLM error: %s", e)
        return {"approved": True}


async def _call_correction_llm(messages: list[dict]) -> str:
    """Asks the LLM to correct the rejected response."""
    from llm import get_provider
    try:
        resp = await get_provider().complete(
            messages=messages,
            temperature=0.4,
            max_tokens=400,
        )
        return resp.text or _SAFE_FALLBACK
    except Exception as e:
        logger.error("Guardrail correction LLM error: %s", e)
        return _SAFE_FALLBACK


def _format_history(history: list[dict], max_messages: int = 10) -> str:
    """Formats the last N messages from the history in a readable form."""
    recent = [m for m in history if m.get("role") in ("user", "assistant")][-max_messages:]
    lines = []
    for m in recent:
        role = "User" if m["role"] == "user" else "NOTHA"
        content = m.get("content") or ""
        if content:
            lines.append(f"{role}: {content[:300]}")
    return "\n".join(lines) if lines else "(no prior history)"


def _last_user_message(history: list[dict]) -> str:
    """Extracts the last user message from the history."""
    for m in reversed(history):
        if m.get("role") == "user" and m.get("content"):
            return m["content"]
    return ""


async def validate_reply(
    reply: str,
    history: list[dict],
    context: str,
    user_message: str = "",
) -> str:
    """
    Validates the generated response before sending to the user.

    Parameters:
      reply        — text generated by the agent
      history      — full conversation history (roles: user/assistant)
      context      — user context string (from _build_context)
      user_message — last user message (if not already in history)

    Returns the original reply if approved, a corrected version if possible,
    or a safe fallback if the problem persists.
    """
    if not reply or not reply.strip():
        logger.warning("Guardrail: empty reply received — using fallback.")
        return _SAFE_FALLBACK

    last_msg = user_message or _last_user_message(history)
    history_fmt = _format_history(history)

    # ── Phase 1: Evaluation ──────────────────────────────────────────────────
    evaluation_prompt = _GUARDRAIL_PROMPT.format(
        context=context or "no context",
        history=history_fmt,
        last_message=last_msg or "(no message)",
        reply=reply,
    )
    result = await _call_guardrail_llm([
        {"role": "user", "content": evaluation_prompt}
    ])

    if result.get("approved", True):
        return reply

    category = result.get("category", "unknown")
    reason = result.get("reason", "no reason specified")
    logger.warning("Guardrail REJECTED — category=%s | reason=%s", category, reason)

    # ── Phase 2: Correction attempt ──────────────────────────────────────────
    correction_prompt = _CORRECTION_PROMPT.format(
        reason=reason,
        category=category,
        context=context or "no context",
        last_message=last_msg or "(no message)",
        rejected_reply=reply,
    )
    corrected_reply = await _call_correction_llm([
        {"role": "user", "content": correction_prompt}
    ])

    # ── Phase 3: Re-evaluate the corrected reply ─────────────────────────────
    re_evaluation_prompt = _GUARDRAIL_PROMPT.format(
        context=context or "no context",
        history=history_fmt,
        last_message=last_msg or "(no message)",
        reply=corrected_reply,
    )
    final_result = await _call_guardrail_llm([
        {"role": "user", "content": re_evaluation_prompt}
    ])

    if final_result.get("approved", True):
        logger.info("Guardrail: corrected reply approved on second attempt.")
        return corrected_reply

    logger.error(
        "Guardrail: corrected reply also rejected — using safe fallback. "
        "category=%s | reason=%s",
        final_result.get("category"),
        final_result.get("reason"),
    )
    return _SAFE_FALLBACK
